- name: Import Google Chrome gpg key
  ansible.builtin.get_url:
    url: '{{ google_chrome_gpg_key_url }}'
    dest: /usr/share/keyrings/google-chrome.asc
    mode: '644'
    owner: root

- name: Ensure Google Chrome repository exists
  ansible.builtin.apt_repository:
    repo: '{{ google_chrome_apt_repository_url }}'
    filename: google-chrome.list
