- name: Import Google Chrome gpg key
  ansible.builtin.apt_key:
    url: '{{ google_chrome_gpg_key }}'
    id: '{{ google_chrome_gpg_key_fingerpint }}'

- name: Ensure Google Chrome repository exists
  ansible.builtin.apt_repository:
    repo: '{{ google_chrome_apt_repository_url }}'
    filename: google-chrome