---
- name: Include os-specific tasks (redhat-family)
  ansible.builtin.include_tasks: '{{ ansible_facts.os_family | lower }}.yml'

- name: Ensure Google Chrome is installed
  ansible.builtin.package:
    name: google-chrome-stable
    state: present
